In [4]:
name ="Jasmine"
hourly_wage = 20.00
hours = 40

weekly_pay = hourly_wage * hours

print(f"{name} earns ${weekly_pay:.2f} per week.")

Jasmine earns $800.00 per week.

In [5]:

temps = [61, 65, 72, 58, 70, 74, 68]

warm_days = 0

for temp in temps:
    if temp > 65:
        warm_days = warm_days + 1

print(warm_days)

4

In [7]:

def to_celsius(f):
    return (f - 32) * 5 / 9

print(round(to_celsius(temps[0]), 1))

16.1

In [8]:

movie = {
    "title": "Black Panther",
    "year": 2018,
    "rating": 7.3
}

for key, value in movie.items():
    print(key, ":", value)

title : Black Panther
year : 2018
rating : 7.3

In [1]:
import pandas as pd

df = pd.read_csv("chickwts.csv")

df.head()

   Unnamed: 0  weight       feed
0           1     179  horsebean
1           2     160  horsebean
2           3     136  horsebean
3           4     227  horsebean
4           5     217  horsebean

In [2]:

df.shape

(71, 3)

In [3]:
ens
df.describe()

       Unnamed: 0      weight
count   71.000000   71.000000
mean    36.000000  261.309859
std     20.639767   78.073700
min      1.000000  108.000000
25%     18.500000  204.500000
50%     36.000000  258.000000
75%     53.500000  323.500000
max     71.000000  423.000000

In [3]:
# The average chicken weight is about 261 grams. The smallest chicken weighed 108 grams, the largest weighed 423 grams. The 315 gram differance surprised me the most, because it showed how much chickens weight varied.